[package]
name = "btclib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
secp256k1 = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
toml = { workspace = true }
dashmap = { workspace = true }
tokio = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
prometheus = { version = "0.13", features = ["process"] }
pqcrypto-dilithium = "0.4.3"
pqcrypto-traits = "0.3.4"
reqwest = { version = "0.11", features = ["json"] }
url = "2.4.0"
hyper = { version = "0.14", features = ["full"] }
curve25519-dalek = "4.1.1"
# Lightning Network dependencies
priority-queue = { version = "1.3.2", optional = true }
bitvec = { version = "1.0.1", optional = true }
bytes = { version = "1.4.0", optional = true }

[features]
default = ["quantum", "environmental", "monitoring"]
quantum = []
environmental = []
monitoring = []
lightning = ["dep:priority-queue", "dep:bitvec", "dep:bytes"]

[[example]]
name = "environmental_demo"
path = "examples/environmental_demo.rs"

[[example]]
name = "filecoin_inspired_env_demo"
path = "examples/filecoin_inspired_env_demo.rs"

[[example]]
name = "emissions_tracking"
path = "examples/emissions_tracking.rs"

[[example]]
name = "lightning_demo"
path = "examples/lightning_demo.rs"
required-features = ["lightning"]

[[example]]
name = "crypto_benchmark"
path = "examples/crypto_benchmark.rs"
