[package]
name = "btclib"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
sha2 = { workspace = true }
bincode = "1.3"
thiserror = { workspace = true }
tracing = { workspace = true }
