# Supernova Clippy Configuration
# Balanced for security and pragmatism

# Maximum cognitive complexity allowed
cognitive-complexity-threshold = 35

# Maximum number of lines allowed per function
too-many-lines-threshold = 150

# Maximum number of arguments allowed per function
too-many-arguments-threshold = 10

# Maximum allowed enum variant size difference
enum-variant-size-threshold = 300

# Minimum supported Rust version
msrv = "1.70.0"
