# Supernova Node Configuration

[node]
chain_id = "supernova-testnet"
environment = "Testnet"
metrics_enabled = true
metrics_port = 9000
log_level = "info"
network_name = "Supernova Testnet"
enable_lightning = true
enable_quantum_security = true

[network]
listen_addr = "/ip4/0.0.0.0/tcp/8333"
max_peers = 50
bootstrap_nodes = []
peer_ping_interval = 30
max_outbound_connections = 24
max_inbound_connections = 128
ban_threshold = 100
ban_duration = 86400
network_id = "supernova-testnet"
enable_mdns = true
enable_upnp = true
enable_peer_exchange = true
enable_nat_traversal = true
connection_timeout = 30
reconnect_interval = 60
status_broadcast_interval = 180
trusted_peers = []
min_outbound_connections = 8

[network.peer_diversity]
enabled = true
min_diversity_score = 0.7
connection_strategy = "BalancedDiversity"
rotation_interval = 21600
max_peers_per_subnet = 3
max_peers_per_asn = 5
max_peers_per_region = 10
max_inbound_ratio = 3.0
max_connection_attempts_per_min = 5

[network.pubsub_config]
history_length = 5
history_gossip = 3
duplicate_cache_size = 1000
duplicate_cache_ttl = 120
heartbeat_interval = 10
validation_mode = "Strict"
max_transmit_size = 5242880
explicit_relays = 3

[storage]
db_path = "./data"
enable_compression = false
cache_size = 536870912
max_open_files = 1000
block_cache_size = 33554432

[mempool]
max_size = 5000
transaction_timeout = 7200
min_fee_rate = 1.0
max_per_address = 100
max_orphan_transactions = 100
enable_rbf = true
min_rbf_fee_increase = 10.0

[backup]
backup_dir = "./backups"
max_backups = 5
backup_interval = 3600
enable_automated_backups = true
compress_backups = true
verify_on_startup = true

[checkpoint]
checkpoints_enabled = true
checkpoint_interval = 86400
checkpoint_type = "Full"
data_dir = "./checkpoints"
max_checkpoints = 7

[api]
enabled = true
bind_address = "127.0.0.1"
port = 8332
cors_allowed_origins = ["*"]
max_request_size = 10485760
rate_limit_per_minute = 60
authentication_required = false
api_keys = []

[testnet]
enabled = true
network_id = "testnet"
enable_faucet = false
faucet_amount = 1000000000000000000
faucet_cooldown = 60
faucet_max_balance = 1000000000000000000
enable_test_mining = false
test_mining_difficulty = 1
enable_network_simulation = false
simulated_latency_ms = 0
simulated_packet_loss = 0.0 