apiVersion: v2
name: supernova
description: SuperNova blockchain network deployment
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: SuperNova Team
    email: support@supernova.network
dependencies:
  - name: prometheus
    version: ~15.10.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: ~6.32.2
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled 