[package]
name = "miner"
version = "0.1.0"
edition = "2021"

[dependencies]
btclib = { path = "../btclib" }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
sha2 = "0.10"
async-trait = "0.1"
bincode = "1.3"