version: '3.8'

services:
  # Seed nodes
  seed-node-1:
    image: supernova:latest
    container_name: supernova-seed-1
    restart: unless-stopped
    ports:
      - "9333:9333"
      - "9332:9332"
    volumes:
      - seed-node-1-data:/data
      - ./config/seed-node-1.toml:/config/node.toml
    environment:
      - NODE_ROLE=seed
      - NODE_NAME=seed-node-1
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    networks:
      - supernova-testnet

  seed-node-2:
    image: supernova:latest
    container_name: supernova-seed-2
    restart: unless-stopped
    ports:
      - "9334:9333"
      - "9335:9332"
    volumes:
      - seed-node-2-data:/data
      - ./config/seed-node-2.toml:/config/node.toml
    environment:
      - NODE_ROLE=seed
      - NODE_NAME=seed-node-2
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    networks:
      - supernova-testnet

  # Mining node
  miner-node:
    image: supernova:latest
    container_name: supernova-miner
    restart: unless-stopped
    ports:
      - "9336:9333"
      - "9337:9332"
    volumes:
      - miner-node-data:/data
      - ./config/miner-node.toml:/config/node.toml
    environment:
      - NODE_ROLE=miner
      - NODE_NAME=miner-node
      - MINE=true
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    networks:
      - supernova-testnet
    depends_on:
      - seed-node-1
      - seed-node-2

  # Faucet service
  faucet:
    image: supernova:latest
    container_name: supernova-faucet
    restart: unless-stopped
    ports:
      - "8080:8080"  # Web UI
      - "9338:9333"  # P2P
      - "9339:9332"  # RPC
    volumes:
      - faucet-data:/data
      - ./config/faucet-node.toml:/config/node.toml
      - ./web/faucet:/web/faucet
    environment:
      - NODE_ROLE=faucet
      - NODE_NAME=faucet-node
      - ENABLE_FAUCET=true
      - FAUCET_WEB_PORT=8080
      - FAUCET_AMOUNT=10000000000  # 100 NOVA
      - FAUCET_COOLDOWN_SECS=3600  # 1 hour
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    networks:
      - supernova-testnet
    depends_on:
      - seed-node-1
      - seed-node-2

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: supernova-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - supernova-testnet

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: supernova-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=supernova
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - supernova-testnet
    depends_on:
      - prometheus

volumes:
  seed-node-1-data:
  seed-node-2-data:
  miner-node-data:
  faucet-data:
  prometheus-data:
  grafana-data:

networks:
  supernova-testnet:
    driver: bridge 