name: Cargo Benchmarks

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'benches/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'benches/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      
      - name: Install Criterion dependencies
        run: sudo apt-get update && sudo apt-get install -y gnuplot

      - name: Check for benchmarks
        id: check_benchmarks
        run: |
          if cargo bench --no-run 2>/dev/null; then
            echo "benchmarks_exist=true" >> $GITHUB_OUTPUT
          else
            echo "benchmarks_exist=false" >> $GITHUB_OUTPUT
            echo "No benchmarks found in the project"
          fi

      - name: Run benchmarks
        if: steps.check_benchmarks.outputs.benchmarks_exist == 'true'
        run: cargo bench -- --output-format bencher | tee benchmark-results.txt
      
      - name: Store benchmark result
        if: steps.check_benchmarks.outputs.benchmarks_exist == 'true'
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: benchmark-results.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@marcjohnson'
      
      - name: Archive benchmark results
        if: steps.check_benchmarks.outputs.benchmarks_exist == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: |
            target/criterion
            benchmark-results.txt 