name: Performance Benchmarks

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or SHA to benchmark'
        required: true
        default: 'main'

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
          
      - uses: Swatinem/rust-cache@v2
          
      - name: Check for benchmarks
        id: check_benchmarks
        run: |
          if cargo bench --no-run 2>/dev/null; then
            echo "benchmarks_exist=true" >> $GITHUB_OUTPUT
          else
            echo "benchmarks_exist=false" >> $GITHUB_OUTPUT
            echo "No benchmarks found in the project"
          fi
          
      - name: Run benchmarks
        if: steps.check_benchmarks.outputs.benchmarks_exist == 'true'
        run: cargo bench -- --output-format bencher | tee benchmark_results.txt
        
      - name: Store benchmark results
        if: steps.check_benchmarks.outputs.benchmarks_exist == 'true'
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Rust Benchmarks
          tool: 'cargo'
          output-file-path: benchmark_results.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: false
          alert-comment-cc-users: '@supernova-core-team' 